// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC241O4Z4HE8Ch202XIx97Jnfe-EcuQGnI',
    appId: '1:196838074266:web:54b09b061accd034d47c23',
    messagingSenderId: '196838074266',
    projectId: 'chat-5a2b6',
    authDomain: 'chat-5a2b6.firebaseapp.com',
    storageBucket: 'chat-5a2b6.appspot.com',
    measurementId: 'G-38VLMX4J6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxwQBzDqX0bV3bk83CLBMDvnaWF039xDo',
    appId: '1:196838074266:android:13c6195928928b9cd47c23',
    messagingSenderId: '196838074266',
    projectId: 'chat-5a2b6',
    storageBucket: 'chat-5a2b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Oerb56ZcmWVjMIvjD6yayQXiUDVnEkE',
    appId: '1:196838074266:ios:b77d930ddf3c9539d47c23',
    messagingSenderId: '196838074266',
    projectId: 'chat-5a2b6',
    storageBucket: 'chat-5a2b6.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4Oerb56ZcmWVjMIvjD6yayQXiUDVnEkE',
    appId: '1:196838074266:ios:1b009e0a6610ec34d47c23',
    messagingSenderId: '196838074266',
    projectId: 'chat-5a2b6',
    storageBucket: 'chat-5a2b6.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
